cargo-features = ["profile-rustflags"]

[package]
name = "rhobos"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rand_xoshiro = "0.7.0"

[profile.native]
inherits = "release"
rustflags = ["-C", "target-cpu=native"]
codegen-units = 1
